export const DEFAULT_EDITOR_ENVIRONMENT_INTENSITY = 1;
export const DEFAULT_EDITOR_BACKGROUND_INTENSITY = 1;
export const DEFAULT_EDITOR_BACKGROUND_BLURRINESS = 0.15;
export const DEFAULT_EDITOR_ENVIRONMENT_ROTATION_Y = 0;
